### ISSUE TITLE
An issue for enabling zoom tools in scadavis.io

### ISSUE THREAD

**Issue by sai-qfes** [riclolsen/node-red-scadavis#2]
Hi,
I am not sure if here is the correct place, butI am writing to you for an issue of SCADAvis.io
When I try to call SCADAvis.io Synoptic API **enableTools**, I found whatever value I gave zoomEnabled, the zoom tools are never enabled. 
https://scadavis.io/synoptic/apidoc/global.html#enableTools

when I read the code of **synopticapi.js**, I found the problem is caused by line 435
https://scadavis.io/synoptic/apidoc/synopticapi.js.html#line426

        if ( typeof zoomEnabled === "undefined" || zoomEnabled )
          zoomEnabled = false;

The two lines set zoomEnabled always to be false. 

As I am not sure if I should submit the issue here, I will also write an email to [scadavis@dscsys.com](mailto:scadavis@dscsys.com)

**Comment by riclolsen** [comment]
Yes that was a problem. It is fixed now.
Thank you very much.
